const StudentTypes = {
  STUDENT_GET_INFO: 'STUDENT_GET_INFO',
  STUDENT_GET_INFO_SUCCESS: 'STUDENT_GET_INFO_SUCCESS',
  STUDENT_GET_INFO_FAILURE: 'STUDENT_GET_INFO_FAILURE',

  STUDENT_UPDATE_INFO: 'STUDENT_UPDATE_INFO',
  STUDENT_UPDATE_INFO_SUCCESS: 'STUDENT_UPDATE_INFO_SUCCESS',
  STUDENT_UPDATE_INFO_FAILURE: 'STUDENT_UPDATE_INFO_FAILURE',
  STUDENT_UPDATE_INFO_CLEAR: 'STUDENT_UPDATE_INFO_CLEAR',
}

export default StudentTypes
