const NotificationTypes = {
  CLEAR_NOTIFICATION_STATE: 'CLEAR_NOTIFICATION_STATE',

  GET_NOTIFICATION_LIST: 'GET_NOTIFICATION_LIST',
  UPDATE_IS_DELETED: 'UPDATE_IS_DELETED',
  GET_NOTIFICATION_LIST_SUCCESS: 'GET_NOTIFICATION_LIST_SUCCESS',
  GET_NOTIFICATION_LIST_FAILURE: 'GET_NOTIFICATION_LIST_FAILURE',
}

export default NotificationTypes
