const TeacherTypes = {
  CLEAR_TEACHER_STATE: 'CLEAR_TEACHER_STATE',

  GET_TEACHER_LIST: 'GET_TEACHER_LIST',
  GET_TEACHER_LIST_SUCCESS: 'GET_TEACHER_LIST_SUCCESS',
  GET_TEACHER_LIST_FAILURE: 'GET_TEACHER_LIST_FAILURE',

  TEACHER_GET_INFO: 'TEACHER_GET_INFO',
  TEACHER_GET_INFO_TO_UPDATE: 'TEACHER_GET_INFO_TO_UPDATE',
  TEACHER_GET_INFO_SUCCESS: 'TEACHER_GET_INFO_SUCCESS',
  TEACHER_GET_INFO_TO_UPDATE_SUCCESS: 'TEACHER_GET_INFO_TO_UPDATE_SUCCESS',
  TEACHER_GET_INFO_FAILURE: 'TEACHER_GET_INFO_FAILURE',

  TEACHER_UPDATE_INFO: 'TEACHER_UPDATE_INFO',
  TEACHER_UPDATE_INFO_SUCCESS: 'TEACHER_UPDATE_INFO_SUCCESS',
  TEACHER_UPDATE_INFO_FAILURE: 'TEACHER_UPDATE_INFO_FAILURE',
  TEACHER_UPDATE_INFO_CLEAR: 'TEACHER_UPDATE_INFO_CLEAR',

  TEACHER_GET_STATISTICS: 'TEACHER_GET_STATISTICS',
  TEACHER_GET_STATISTICS_SUCCESS: 'TEACHER_GET_STATISTICS_SUCCESS',
  TEACHER_GET_STATISTICS_FAILURE: 'TEACHER_GET_STATISTICS_FAILURE',

  TEACHER_GET_STATISTICS_HOME: 'TEACHER_GET_STATISTICS_HOME',

  TEACHER_SEARCH: 'TEACHER_SEARCH',
  TEACHER_SEARCH_SUCCESSS: 'TEACHER_SEARCH_SUCCESSS',
  TEACHER_SEARCH_FAILURE: 'TEACHER_SEARCH_FAILURE',
  TEACHER_SEARCH_CLEAR: 'TEACHER_SEARCH_CLEAR',
}

export default TeacherTypes
